//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CF_SYSTEM_CONFIG
    {
        public long system_config_id { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string db_setting { get; set; }
        public string db_purchase { get; set; }
        public string db_sales { get; set; }
        public string db_wms { get; set; }
        public string db_inventory { get; set; }
        public string db_transportation { get; set; }
        public string db_prodction { get; set; }
        public string db_planning { get; set; }
    }
}
