//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MS_MENU()
        {
            this.MS_ROLE_MENU = new HashSet<MS_ROLE_MENU>();
        }
    
        public long menu_id { get; set; }
        public string created_by { get; set; }
        public System.DateTime creaed_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public long system_id { get; set; }
        public string menu_name { get; set; }
        public string can_edit { get; set; }
        public string can_delete { get; set; }
        public string menu_url { get; set; }
        public string css_menu_icon { get; set; }
        public int menu_seq { get; set; }
        public long parent_menu_id { get; set; }
        public string active_status { get; set; }
    
        public virtual MS_SYSTEM MS_SYSTEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MS_ROLE_MENU> MS_ROLE_MENU { get; set; }
    }
}
