//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_ROLE_USER
    {
        public long role_user_id { get; set; }
        public string created_by { get; set; }
        public System.DateTime creaed_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public long role_id { get; set; }
        public long user_id { get; set; }
    
        public virtual MS_ROLE MS_ROLE { get; set; }
        public virtual MS_USER MS_USER { get; set; }
    }
}
