//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHANGE_PSSWD_HISTORY
    {
        public long change_psswd_history_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> creaed_date { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public System.DateTime change_time { get; set; }
        public string username { get; set; }
        public string system_code { get; set; }
        public string old_psswd { get; set; }
        public string new_psswd { get; set; }
    }
}
