//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด.
        /// </summary>
        public static string Ddl_Action_All {
            get {
                return ResourceManager.GetString("Ddl_Action_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Ddl_AttachFile_No {
            get {
                return ResourceManager.GetString("Ddl_AttachFile_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Ddl_AttachFile_Yes {
            get {
                return ResourceManager.GetString("Ddl_AttachFile_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto complete.
        /// </summary>
        public static string Ddl_AutoComplete {
            get {
                return ResourceManager.GetString("Ddl_AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- กรุณาระบุ --.
        /// </summary>
        public static string Ddl_PleaseSelect {
            get {
                return ResourceManager.GetString("Ddl_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Ddl_Status_Active {
            get {
                return ResourceManager.GetString("Ddl_Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทั้งหมด.
        /// </summary>
        public static string Ddl_Status_All {
            get {
                return ResourceManager.GetString("Ddl_Status_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Ddl_Status_Fail {
            get {
                return ResourceManager.GetString("Ddl_Status_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-active.
        /// </summary>
        public static string Ddl_Status_Inactive {
            get {
                return ResourceManager.GetString("Ddl_Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Ddl_Status_Success {
            get {
                return ResourceManager.GetString("Ddl_Status_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Ddl_VerifyResult_Fail {
            get {
                return ResourceManager.GetString("Ddl_VerifyResult_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string Ddl_VerifyResult_Pass {
            get {
                return ResourceManager.GetString("Ddl_VerifyResult_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string Ddl_VerifyResult_Skip {
            get {
                return ResourceManager.GetString("Ddl_VerifyResult_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลไม่สำเร็จ.
        /// </summary>
        public static string Error_SaveFailed {
            get {
                return ResourceManager.GetString("Error_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล์ที่ระบุถูกใช้งานแล้ว กรุณาตรวจสอบข้อมูล.
        /// </summary>
        public static string Error_SaveFailed_CommPoolDuplicate {
            get {
                return ResourceManager.GetString("Error_SaveFailed_CommPoolDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบข้อมูลในระบบ กรุณาตรวจสอบ.
        /// </summary>
        public static string Error_SaveFailedDuplicate {
            get {
                return ResourceManager.GetString("Error_SaveFailedDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่อกับระบบได้ กรุณาตรวจสอบอีกครั้ง.
        /// </summary>
        public static string Error_System {
            get {
                return ResourceManager.GetString("Error_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to access this part of the site.&lt;br /&gt;Please contact system administrator or IT support for assistance..
        /// </summary>
        public static string Lbl_AccessDenied {
            get {
                return ResourceManager.GetString("Lbl_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Date From.
        /// </summary>
        public static string Lbl_ActionDateFrom {
            get {
                return ResourceManager.GetString("Lbl_ActionDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Date To.
        /// </summary>
        public static string Lbl_ActionDateTo {
            get {
                return ResourceManager.GetString("Lbl_ActionDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประกาศเมื่อวันที่.
        /// </summary>
        public static string Lbl_AnnounceDate {
            get {
                return ResourceManager.GetString("Lbl_AnnounceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Lbl_Area {
            get {
                return ResourceManager.GetString("Lbl_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำอธิบายเอกสาร.
        /// </summary>
        public static string Lbl_AttachDesc {
            get {
                return ResourceManager.GetString("Lbl_AttachDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อเอกสาร.
        /// </summary>
        public static string Lbl_AttachName {
            get {
                return ResourceManager.GetString("Lbl_AttachName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สาขา.
        /// </summary>
        public static string Lbl_Branch {
            get {
                return ResourceManager.GetString("Lbl_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่บัตร ปชช.
        /// </summary>
        public static string Lbl_CardNo {
            get {
                return ResourceManager.GetString("Lbl_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่หนังสือเดินทาง.
        /// </summary>
        public static string Lbl_CardNo_Passport {
            get {
                return ResourceManager.GetString("Lbl_CardNo_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปลี่ยนรหัสผ่าน.
        /// </summary>
        public static string Lbl_ChangePsswd {
            get {
                return ResourceManager.GetString("Lbl_ChangePsswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Lbl_ConfirmPasswd {
            get {
                return ResourceManager.GetString("Lbl_ConfirmPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy; {0}{1}.
        /// </summary>
        public static string Lbl_Copyright {
            get {
                return ResourceManager.GetString("Lbl_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Lbl_Customer {
            get {
                return ResourceManager.GetString("Lbl_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Profile Information.
        /// </summary>
        public static string Lbl_CustomerInformation {
            get {
                return ResourceManager.GetString("Lbl_CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อลูกค้า.
        /// </summary>
        public static string Lbl_CustomerName {
            get {
                return ResourceManager.GetString("Lbl_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string Lbl_CustomerSurname {
            get {
                return ResourceManager.GetString("Lbl_CustomerSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียด.
        /// </summary>
        public static string Lbl_Detail {
            get {
                return ResourceManager.GetString("Lbl_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่มีผล.
        /// </summary>
        public static string Lbl_EffectiveDate {
            get {
                return ResourceManager.GetString("Lbl_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Lbl_Email {
            get {
                return ResourceManager.GetString("Lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสพนักงาน.
        /// </summary>
        public static string Lbl_EmployeeCode {
            get {
                return ResourceManager.GetString("Lbl_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่หมดอายุ.
        /// </summary>
        public static string Lbl_ExpiryDate {
            get {
                return ResourceManager.GetString("Lbl_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์แฟกซ์.
        /// </summary>
        public static string Lbl_Fax {
            get {
                return ResourceManager.GetString("Lbl_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสารที่อัพโหลด.
        /// </summary>
        public static string Lbl_FileAttach {
            get {
                return ResourceManager.GetString("Lbl_FileAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string Lbl_FirstName {
            get {
                return ResourceManager.GetString("Lbl_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Lbl_FirstNameEnglish {
            get {
                return ResourceManager.GetString("Lbl_FirstNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ติดต่อ.
        /// </summary>
        public static string Lbl_FirstNameThai_Contact {
            get {
                return ResourceManager.GetString("Lbl_FirstNameThai_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อลูกค้า.
        /// </summary>
        public static string Lbl_FirstNameThai_Customer {
            get {
                return ResourceManager.GetString("Lbl_FirstNameThai_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Lbl_Home {
            get {
                return ResourceManager.GetString("Lbl_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปภาพที่อัพโหลด.
        /// </summary>
        public static string Lbl_ImageAttach {
            get {
                return ResourceManager.GetString("Lbl_ImageAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สนใจ/ไม่สนใจ.
        /// </summary>
        public static string Lbl_Interested {
            get {
                return ResourceManager.GetString("Lbl_Interested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string Lbl_LastName {
            get {
                return ResourceManager.GetString("Lbl_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Lbl_LastNameEnglish {
            get {
                return ResourceManager.GetString("Lbl_LastNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุลผู้ติดต่อ.
        /// </summary>
        public static string Lbl_LastNameThai_Contact {
            get {
                return ResourceManager.GetString("Lbl_LastNameThai_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุลลูกค้า.
        /// </summary>
        public static string Lbl_LastNameThai_Customer {
            get {
                return ResourceManager.GetString("Lbl_LastNameThai_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าที่.
        /// </summary>
        public static string Lbl_PageNo {
            get {
                return ResourceManager.GetString("Lbl_PageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการที่ {0}-{1} จากรายการทั้งหมด {2}.
        /// </summary>
        public static string Lbl_Paging {
            get {
                return ResourceManager.GetString("Lbl_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Lbl_Password {
            get {
                return ResourceManager.GetString("Lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์.
        /// </summary>
        public static string Lbl_PhoneNo {
            get {
                return ResourceManager.GetString("Lbl_PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Name.
        /// </summary>
        public static string Lbl_PoolName {
            get {
                return ResourceManager.GetString("Lbl_PoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Lbl_Product {
            get {
                return ResourceManager.GetString("Lbl_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        public static string Lbl_ProductGroup {
            get {
                return ResourceManager.GetString("Lbl_ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดความสัมพันธ์.
        /// </summary>
        public static string Lbl_RelationDesc {
            get {
                return ResourceManager.GetString("Lbl_RelationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อความสัมพันธ์.
        /// </summary>
        public static string Lbl_RelationName {
            get {
                return ResourceManager.GetString("Lbl_RelationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ความสัมพันธ์.
        /// </summary>
        public static string Lbl_Relationship {
            get {
                return ResourceManager.GetString("Lbl_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Lbl_Remark {
            get {
                return ResourceManager.GetString("Lbl_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Communication Pool.
        /// </summary>
        public static string Lbl_Report_CommPool {
            get {
                return ResourceManager.GetString("Lbl_Report_CommPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for NCB.
        /// </summary>
        public static string Lbl_Report_NCB {
            get {
                return ResourceManager.GetString("Lbl_Report_NCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report SR.
        /// </summary>
        public static string Lbl_Report_SR {
            get {
                return ResourceManager.GetString("Lbl_Report_SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Verify.
        /// </summary>
        public static string Lbl_Report_Verify {
            get {
                return ResourceManager.GetString("Lbl_Report_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Verify Detail.
        /// </summary>
        public static string Lbl_Report_VerifyDetail {
            get {
                return ResourceManager.GetString("Lbl_Report_VerifyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Lbl_Reports {
            get {
                return ResourceManager.GetString("Lbl_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string Lbl_RoleName {
            get {
                return ResourceManager.GetString("Lbl_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Lbl_Status {
            get {
                return ResourceManager.GetString("Lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ.
        /// </summary>
        public static string Lbl_Status_Thai {
            get {
                return ResourceManager.GetString("Lbl_Status_Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อระบบ.
        /// </summary>
        public static string Lbl_SystemName {
            get {
                return ResourceManager.GetString("Lbl_SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Lbl_Topic {
            get {
                return ResourceManager.GetString("Lbl_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Lbl_Type {
            get {
                return ResourceManager.GetString("Lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Lbl_Url {
            get {
                return ResourceManager.GetString("Lbl_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Lbl_Username {
            get {
                return ResourceManager.GetString("Lbl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่อฐานข้อมูล  กรุณาติดต่อ system administrator.
        /// </summary>
        public static string Msg_CannotConnectToDB {
            get {
                return ResourceManager.GetString("Msg_CannotConnectToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลอย่างน้อย 1 เงื่อนไข.
        /// </summary>
        public static string Msg_EnteredAtLeastOneCriteria {
            get {
                return ResourceManager.GetString("Msg_EnteredAtLeastOneCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุรหัสผ่านใหม่.
        /// </summary>
        public static string Msg_EnteredNewPassword {
            get {
                return ResourceManager.GetString("Msg_EnteredNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุรหัสผ่านเดิม.
        /// </summary>
        public static string Msg_EnteredOldPassword {
            get {
                return ResourceManager.GetString("Msg_EnteredOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หญิง.
        /// </summary>
        public static string Msg_GenderFemale {
            get {
                return ResourceManager.GetString("Msg_GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชาย.
        /// </summary>
        public static string Msg_GenderMale {
            get {
                return ResourceManager.GetString("Msg_GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สนใจ.
        /// </summary>
        public static string Msg_Interested {
            get {
                return ResourceManager.GetString("Msg_Interested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การยืนยันรหัสผานใหม่ไม่ถูกต้อง.
        /// </summary>
        public static string Msg_InvalidConfirmPassword {
            get {
                return ResourceManager.GetString("Msg_InvalidConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านไม่ถูกต้อง.
        /// </summary>
        public static string Msg_InvalidPassword {
            get {
                return ResourceManager.GetString("Msg_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาตรวจสอบ username หรือ password.
        /// </summary>
        public static string Msg_LoginFailed {
            get {
                return ResourceManager.GetString("Msg_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณใส่รหัสผ่านผิดเกิน {0} ครั้ง กรุณาติดต่อผู้ดูแลระบบ.
        /// </summary>
        public static string Msg_LoginMaxFail {
            get {
                return ResourceManager.GetString("Msg_LoginMaxFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สนใจ.
        /// </summary>
        public static string Msg_NoInterested {
            get {
                return ResourceManager.GetString("Msg_NoInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล.
        /// </summary>
        public static string Msg_NoRecords {
            get {
                return ResourceManager.GetString("Msg_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบสิทธิ์ในการเข้าใช้ระบบ กรุณาติดต่อ system administrator.
        /// </summary>
        public static string Msg_UserRoleNotFound {
            get {
                return ResourceManager.GetString("Msg_UserRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xlsx.
        /// </summary>
        public static string Report_FileExtention {
            get {
                return ResourceManager.GetString("Report_FileExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เมนูหลัก.
        /// </summary>
        public static string Title_MainMenu {
            get {
                return ResourceManager.GetString("Title_MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string Title_Master {
            get {
                return ResourceManager.GetString("Title_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Title_Role {
            get {
                return ResourceManager.GetString("Title_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Title_User {
            get {
                return ResourceManager.GetString("Title_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือกอย่างน้อย 1 รายการ.
        /// </summary>
        public static string ValErr_AtLeastOneItem {
            get {
                return ResourceManager.GetString("ValErr_AtLeastOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเลือก{0}อย่างน้อย 1 รายการ.
        /// </summary>
        public static string ValErr_AtLeastOneItemWithField {
            get {
                return ResourceManager.GetString("ValErr_AtLeastOneItemWithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องกรอกอย่างน้อย 2 ตัวอักษร.
        /// </summary>
        public static string ValErr_AtLeastTwoDigits {
            get {
                return ResourceManager.GetString("ValErr_AtLeastTwoDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input wrong format.
        /// </summary>
        public static string ValErr_ContainHtmlTags {
            get {
                return ResourceManager.GetString("ValErr_ContainHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription ID ที่ระบุไม่ถูกต้อง กรุณาตรวจสอบข้อมูล.
        /// </summary>
        public static string ValErr_InvalidCardNo {
            get {
                return ResourceManager.GetString("ValErr_InvalidCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุวันที่ให้ถูกต้อง.
        /// </summary>
        public static string ValErr_InvalidDate {
            get {
                return ResourceManager.GetString("ValErr_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ต้องน้อยกว่าหรือเท่ากับวันที่ปัจจุบัน.
        /// </summary>
        public static string ValErr_InvalidDate_MustLessThanToday {
            get {
                return ResourceManager.GetString("ValErr_InvalidDate_MustLessThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ต้องมากกว่าหรือเท่ากับวันที่ปัจจุบัน.
        /// </summary>
        public static string ValErr_InvalidDate_MustMoreThanToday {
            get {
                return ResourceManager.GetString("ValErr_InvalidDate_MustMoreThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สิ้นสุดต้องมากกว่าวันที่เริ่มต้น.
        /// </summary>
        public static string ValErr_InvalidDateRange {
            get {
                return ResourceManager.GetString("ValErr_InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล์ที่ระบุไม่ถูกต้อง กรุณาตรวจสอบข้อมูล.
        /// </summary>
        public static string ValErr_InvalidEmail {
            get {
                return ResourceManager.GetString("ValErr_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีมล์ต้องอยู่ในโดเมน kiatnakin.co.th เท่านั้น.
        /// </summary>
        public static string ValErr_InvalidEmailDomain {
            get {
                return ResourceManager.GetString("ValErr_InvalidEmailDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject อีเมล์ไม่ถูกต้อง.
        /// </summary>
        public static string ValErr_InvalidEmailSubject {
            get {
                return ResourceManager.GetString("ValErr_InvalidEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาไม่ถูกต้อง.
        /// </summary>
        public static string ValErr_InvalidTimeFormat {
            get {
                return ResourceManager.GetString("ValErr_InvalidTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาสิ้นสุดต้องมากกว่าเวลาเริ่มต้น.
        /// </summary>
        public static string ValErr_InvalidTimeRange {
            get {
                return ResourceManager.GetString("ValErr_InvalidTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL ที่ระบุไม่ถูกต้อง กรุณาตรวจสอบข้อมูล.
        /// </summary>
        public static string ValErr_InvalidURL {
            get {
                return ResourceManager.GetString("ValErr_InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องกรอกอย่างน้อย {0} ตัวอักษร.
        /// </summary>
        public static string ValErr_MinLength {
            get {
                return ResourceManager.GetString("ValErr_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุข้อมูลภาษาอังกฤษเและอักขระที่กำหนด.
        /// </summary>
        public static string ValErr_NoSpecialCharacterEnglish {
            get {
                return ResourceManager.GetString("ValErr_NoSpecialCharacterEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุข้อมูลภาษาไทยเและอักขระที่กำหนด.
        /// </summary>
        public static string ValErr_NoSpecialCharacterThai {
            get {
                return ResourceManager.GetString("ValErr_NoSpecialCharacterThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลที่กรอกต้องเป็นตัวเลขและ # เท่านั้น.
        /// </summary>
        public static string ValErr_NumericAndExtOnly {
            get {
                return ResourceManager.GetString("ValErr_NumericAndExtOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลที่กรอกต้องเป็นตัวเลขเท่านั้น.
        /// </summary>
        public static string ValErr_NumericOnly {
            get {
                return ResourceManager.GetString("ValErr_NumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุยอมรับว่าอ่านเอกสารเรียบร้อยแล้ว ก่อนกดปุ่ม Save.
        /// </summary>
        public static string ValErr_PleaseAcceptNews {
            get {
                return ResourceManager.GetString("ValErr_PleaseAcceptNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ท่านสามารถ Export ข้อมูลได้ก่อน {0} และหลัง {1}.
        /// </summary>
        public static string ValErr_ReportTime {
            get {
                return ResourceManager.GetString("ValErr_ReportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify report start time and end time configuration..
        /// </summary>
        public static string ValErr_ReportTimeConfiguration {
            get {
                return ResourceManager.GetString("ValErr_ReportTimeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูล.
        /// </summary>
        public static string ValErr_Required {
            get {
                return ResourceManager.GetString("ValErr_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุ {0}.
        /// </summary>
        public static string ValErr_RequiredField {
            get {
                return ResourceManager.GetString("ValErr_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ต้องไม่เกิน {1} ตัวอักษร.
        /// </summary>
        public static string ValErr_StringLength {
            get {
                return ResourceManager.GetString("ValErr_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถบันทึกข้อมูลได้ เนื่องจากพบข้อมูลลูกค้าที่ใช้ Subscription Type และ Subscription ID เดียวกัน.
        /// </summary>
        public static string ValError_DuplicateCardNo {
            get {
                return ResourceManager.GetString("ValError_DuplicateCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถบันทึกข้อมูลผู้ติดต่อได้ เนื่องจากพบข้อมูลผู้ติดต่อซ้ำในระบบ.
        /// </summary>
        public static string ValError_DuplicateContact {
            get {
                return ResourceManager.GetString("ValError_DuplicateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทรศัพท์ ซ้ำกัน.
        /// </summary>
        public static string ValError_DuplicatePhoneNo {
            get {
                return ResourceManager.GetString("ValError_DuplicatePhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทเอกสารที่อัพโหลดไม่ถูกต้อง.
        /// </summary>
        public static string ValError_FileExtension {
            get {
                return ResourceManager.GetString("ValError_FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทไฟล์ของ Displayed Image ไม่ถูกต้อง.
        /// </summary>
        public static string ValError_FileExtensionConfigUrl {
            get {
                return ResourceManager.GetString("ValError_FileExtensionConfigUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดเอกสารที่ต้องการอัพโหลด เกินกำหนด (5MB).
        /// </summary>
        public static string ValError_FileSizeExceedMaxLimit {
            get {
                return ResourceManager.GetString("ValError_FileSizeExceedMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดเอกสารที่อัพโหลด มีขนาดเกินกว่าที่ระบบกำหนดไว้.
        /// </summary>
        public static string ValError_FileSizeExceedServerMaxLimit {
            get {
                return ResourceManager.GetString("ValError_FileSizeExceedServerMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไฟล์ Displayed Image มีขนาดเกินกำหนด (1MB).
        /// </summary>
        public static string ValError_FileSizeUploadMaxLimit {
            get {
                return ResourceManager.GetString("ValError_FileSizeUploadMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่านไม่ตรงกับยืนยันรหัสผ่าน กรุณากรอกใหม่อีกครั้ง.
        /// </summary>
        public static string ValError_InvalidConfirmPasswd {
            get {
                return ResourceManager.GetString("ValError_InvalidConfirmPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่เริ่มต้น - วันที่สิ้นสุดต้องอยู่ช่วง {0} เดือน.
        /// </summary>
        public static string ValError_ReportExportDuration {
            get {
                return ResourceManager.GetString("ValError_ReportExportDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดเอกสารที่ต้องการอัพโหลด เกินกำหนด ({0}MB).
        /// </summary>
        public static string ValError_SingleFileSizeExceedMaxLimit {
            get {
                return ResourceManager.GetString("ValError_SingleFileSizeExceedMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดเอกสารที่ต้องการอัพโหลดรวมกับไฟล์อื่นๆ เกินกำหนด ({0}MB).
        /// </summary>
        public static string ValError_TotalFileSizeExceedMaxLimit {
            get {
                return ResourceManager.GetString("ValError_TotalFileSizeExceedMaxLimit", resourceCulture);
            }
        }
    }
}
